### ISSUE TITLE
overflow problem when inside popup

### ISSUE THREAD

**Issue by tarlepp** [evoluteur/colorpicker#9]
Hi I just started to using this awesome component in my application. I noticed that component doesn't work correctly with modals, screenshot below

![image](https://f.cloud.github.com/assets/595561/1843540/94118136-74d5-11e3-83c1-9699a5af4072.png)

I would be very happy if you could fix this.

**Comment by deneektolentino** [comment]
im having this problem as well inside a jquery ui dialog
![screen shot 2015-02-15 at 5 56 34 pm](https://cloud.githubusercontent.com/assets/8186436/6202850/1cdc3ed2-b53c-11e4-9420-2399d8f594ba.png)
![screen shot 2015-02-15 at 5 56 43 pm](https://cloud.githubusercontent.com/assets/8186436/6202851/1ede65f2-b53c-11e4-95c8-c877555cab3f.png)


my question is - can the popup appear at the top of the input box rather than the bottom?

**Comment by deneektolentino** [comment]
i added a css so that it appears on top instead of the bottom, its not a real fix but it would to for now

```css
.evo-pop {
    bottom: 0;
}
```

 although it would only be useful if the color input box is at the bottom part of the dialog modal.
![screen shot 2015-02-15 at 6 27 37 pm](https://cloud.githubusercontent.com/assets/8186436/6202937/59ef9fe0-b540-11e4-9ec0-f2ec80cb8a04.png)

**Comment by tarlepp** [comment]
So it this fixed now?

**Comment by evoluteur** [comment]
Sorry, no, it's not fixed but I decided not to fix it. 
It's not trivial and outside of the normal usage.

**Comment by tarlepp** [comment]
ok, thanks for that info need to find another library for this :(

**Comment by Kenneth-Chan** [comment]
You can modify the following function in evol.colorpicker.js source code.  You could try converting it a prototype function or extend without changing the source code.

      	_create: function() {
                ..............................
                 // change the following code to pass the evt to show palette
		if(showOn==='both' || showOn==='button'){
					e.next().on('click', function(evt){
						evt.stopPropagation();
						that.showPalette(evt);
					});
				}
                         }               
                 }
                  ....................
      

      showPalette: function (e) {	    
		if(this._enabled){
			this._active=true;
			$('.colorPicker').not('.'+this._id).colorpicker('hidePalette');
			if(this._palette===null){
			    this._palette = $('#YOUR_DIALOG_DIV_ID')                                        
                    .after(this._paletteHTML()).next()
                    .css({ top: e.clientY + 'px', left: e.clientX + 'px', position: 'absolute' })
					.on('click',function(evt){
						evt.stopPropagation();
					});
				this._bindColors();
				var that=this;
				if(this._isPopup){
					$(document.body).on('click.'+that._id, function(evt){
						if(evt.target!=that.element.get(0)){
							that.hidePalette();
						}
					}).on('keyup.'+that._id, function(evt){
						if(evt.keyCode===27){
							that.hidePalette();
						}
					});
				}
			}
		}
		return this;
	},

**Comment by tarlepp** [comment]
@Kenneth-Chan nice one, you should make a PR about this with extra option ```appendToBody: true``` which changes behaviour to this.
